### PR TITLE
chore: update trivy to 0.45.0

### PR DESCRIPTION
**Pull request by meysam81**

### CODE REVIEW

**Comment by meysam81** [comment]
The second commit is a bugfix. I ran my pre-commit, and it complained about not having a `PATH` set, as seen in the screenshot below.

image

**Comment by mxab** [comment]
Hi @meysam81 , sorry I somehow missed your PR. I just merged another one with an even newer version.

**Comment by mxab** [comment]
@meysam81 regarding the `.`, doesn't it work if you add the dot at the end of your config

e.g.:

```yaml
    -   id: trivyfs-docker
        args:
          - --skip-dirs
          - ./tests
          - . # last arg indicates the path/file to scan
```

**Comment by meysam81** [comment]
Yeah, that solved it. Thanks :pray:

**Pull request closed without merging**
